### ISSUE TITLE
Implement posting of contact message

### ISSUE THREAD

**Issue by Ahmzyjazzy** [hnginternship5/apoe4#25]

**Comment by oyewoas** [comment]
can i know what this really entails?? @Ahmzyjazzy

**Comment by seyicole** [comment]
Is like i cant assign issue to myself. I can handle this though.

**Comment by Ahmzyjazzy** [comment]
Leyota suggest we only have address detail and user can click on send mail to use 
mailto. For example
```<A HREF="mailto:name@mydomain.com">Send Email</A>```
have implemented this.
