### ISSUE TITLE
Add link to learn more button.

### ISSUE THREAD

**Issue by Ahmzyjazzy** [hnginternship5/apoe4#30]
You can load a blank page that has information to search about Azheimers. sample link https://g.co/kgs/jPU8gC

**Comment by damikanye** [comment]
will do this
 but will I add this to the landing page or where @Ahmzyjazzy

**Comment by Ahmzyjazzy** [comment]
Landing page, you can make it load in an iframe. The iframe can be a modal. So that we still have this on our page rather than separate tab.

**Comment by damikanye** [comment]
okay

**Comment by Ahmzyjazzy** [comment]
Waiting for your update on this one.

**Comment by damikanye** [comment]
I'm coming

**Comment by damikanye** [comment]
have sent a pull request
