### ISSUE TITLE
Home page - welcome section

### ISSUE THREAD

**Issue by Ahmzyjazzy** [hnginternship5/apoe4#53]
You will find the file inside src/components/home/WelcomeSection.vue

![image](https://user-images.githubusercontent.com/24432247/56252693-df659d80-60b0-11e9-98d0-1db2882c260f.png)

**Comment by oyewoas** [comment]
hi @Ahmzyjazzy , my slack name is @oyewoas and i will be working on this.

**Comment by Ahmzyjazzy** [comment]
ok
